import { PropertyData } from '@/components/property/PropertyCard';

export const mockProperties: PropertyData[] = [
  {
    _id: '1',
    title: '3 BHK Park Facing Independent House in Avas Vikas Colony',
    slug: '3-bhk-park-facing-independent-house-in-avas-vikas-colony-avas-vikas-agra',
    description: 'Newly built modern 3 BHK duplex independent house situated in the prime location of Avas Vikas Colony, Agra. This ADA approved property is west facing and directly park facing, located on a wide 30 ft road. Built on a 75 Sq Yards plot, it offers spacious bedrooms, elegant interior woodwork, stylish stainless steel balcony railings, designer iron main gates, and dedicated car ramp & parking. Ready to move with clear legal title and documentation.',
    price: 7500000,
    propertyType: 'house',
    bhk: 3,
    plotSize: '75 Sq Yards',
    address: 'Sector 7, Avas Vikas Colony, Near Central Park',
    locality: 'Avas Vikas',
    city: 'Agra',
    state: 'Uttar Pradesh',
    images: ['/properties/avas-vikas-3bhk-house.jpg'],
    status: 'available',
    featured: true,
    views: 185,
    contactNumber: '+91 97565 35933',
    whatsappNumber: '+91 97565 35933',
    coordinates: { lat: 27.2144, lng: 78.0289 },
    nearbySchools: ['Milton Public School', 'St. Clares Senior Secondary School', 'Delhi Public School Agra'],
    nearbyHospitals: ['Pushpanjali Hospital', 'Upadhyay Hospital', 'Rainbow Hospital'],
    nearbyMarkets: ['Avas Vikas Local Market', 'Sikandra Commercial Hub', 'Bodhaki Road Market'],
    parking: true,
    waterSupply: '24 Hours Supply + Submersible',
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z'
  },
  {
    _id: '2',
    title: 'Industrial Warehouse / Commercial Shed on Rent (3000 to 10000 Sq Ft)',
    slug: 'industrial-warehouse-commercial-shed-on-rent-kuberpur-agra',
    description: 'Prime industrial warehouse & commercial shed available for rent on Main Kanpur-Agra Highway (NH-19), near Kuberpur, Agra. Flexible covered space available from 3,000 Sq Ft up to 10,000 Sq Ft at an attractive rate of ₹20/Sq Ft with full industrial electricity connection & water connection included ("Connection Sahit"). Features high ceiling steel PEB structure, heavy-duty paved flooring for multi-axle trucks/trailers, built-in office cabin, and wide sliding gate entry with immediate connectivity to Agra-Lucknow and Yamuna Expressways.',
    price: 60000, // Starts at 60k/month (3000 sq ft @ ₹20/sq ft)
    propertyType: 'rent',
    plotSize: '3000 - 10000 Sq Ft',
    address: 'Main Kanpur-Agra Highway (NH-19), Near Kuberpur Toll Plaza & Outer Ring Road',
    locality: 'Kuberpur',
    city: 'Agra',
    state: 'Uttar Pradesh',
    images: [
      '/properties/warehouse-kuberpur-1.png',
      '/properties/warehouse-kuberpur-2.jpg',
      '/properties/warehouse-kuberpur-3.jpg',
      '/properties/warehouse-kuberpur-4.png'
    ],
    status: 'available',
    featured: true,
    views: 140,
    contactNumber: '+91 97565 35933',
    whatsappNumber: '+91 97565 35933',
    coordinates: { lat: 27.2289, lng: 78.1154 },
    nearbySchools: ['Transport Nagar Logistics Hub', 'Kuberpur Industrial Belt'],
    nearbyHospitals: ['Highway Trauma Center Kuberpur', 'Emergency Medical Center'],
    nearbyMarkets: ['Kuberpur Wholesale Market', 'Transport Nagar Hub', 'Agra Grain Market'],
    parking: true,
    waterSupply: '24 Hours Water & Heavy Electricity Connection',
    createdAt: '2026-09-12T11:55:00Z',
    updatedAt: '2026-09-12T11:55:00Z'
  },
  {
    _id: '3',
    title: 'Luxury 3 BHK Duplex Villa in Gated Society, Shastripuram',
    slug: 'luxury-3-bhk-duplex-villa-in-gated-society-shastripuram-agra',
    description: 'Brand new ultra-modern 3 BHK duplex luxury villa located in a premium gated society at prime location of Shastripuram, Agra. Built on 100 Sq. Yards plot with contemporary elevation, fluted concrete architectural wall finishes, frameless glass balcony railings, and individual car ramp & parking. Interior features premium vitrified flooring, designer false ceiling with warm ambient LED strip lighting, modular bathrooms with wall-hung commodes & luxury quartz vanity, and stainless steel staircase railings. Society offers 24x7 security, lush green central park with children\'s play area / slides, wide concrete roads, and uninterrupted water supply.',
    price: 11200000, // 1.12 Crore
    propertyType: 'house',
    bhk: 3,
    plotSize: '100 Sq Yards',
    address: 'Palm Green Enclave, Sector C, Main Shastripuram',
    locality: 'Shastripuram',
    city: 'Agra',
    state: 'Uttar Pradesh',
    images: [
      '/properties/shastripuram-villa-1.png',
      '/properties/shastripuram-villa-6.png',
      '/properties/shastripuram-villa-2.png',
      '/properties/shastripuram-villa-3.png',
      '/properties/shastripuram-villa-4.png',
      '/properties/shastripuram-villa-7.jpg',
      '/properties/shastripuram-villa-5.jpg'
    ],
    status: 'available',
    featured: true,
    views: 165,
    contactNumber: '+91 97565 35933',
    whatsappNumber: '+91 97565 35933',
    coordinates: { lat: 27.1892, lng: 77.9825 },
    nearbySchools: ['Holy Public School', 'Shastripuram Academy', 'St. Andrews Public School'],
    nearbyHospitals: ['Jaikrishan Hospital', 'Grover Hospital', 'Rainbow Hospital'],
    nearbyMarkets: ['Shastripuram Central Plaza', 'Sikandra Crossing Market', 'Westend Mall'],
    parking: true,
    waterSupply: '24 Hours Society Overhead Reservoir & Ganga Jal',
    createdAt: '2026-09-12T12:15:00Z',
    updatedAt: '2026-09-12T12:15:00Z'
  },
  {
    _id: '4',
    title: 'Operational Educational Institution / College Campus (10,185 Sq Mtr Land)',
    slug: 'operational-educational-institution-college-campus-bamrauli-katara-fatehabad-road-agra',
    description: 'Fully operational and approved educational institution / college campus situated in prime location of Bamrauli Katara, near Hotel Ramada Plaza, off Main Fatehabad Road, Agra. Spanning a vast 10,185 Sq. Meters of lush green land (~2.51 Acres) with approx. 60,000 Sq. Ft. of built-up institutional construction.\n\nApproved Courses & Infrastructure:\n• Approved Courses: B.Ed (100 Seats) & BTC / D.El.Ed (50 Seats)\n• Infrastructure: Complete Library, furniture for 500+ students, and small transport van\n• Legal Status: Registered under Society Act with valid 80G & 12A tax exemption certificates\n• Campus: Beautiful landscaped gardens, paved pathways, vertical ivy green walls, spacious corridors & office blocks.',
    price: 0, // Price on Request
    propertyType: 'commercial',
    plotSize: '10,185 Sq Mtrs (~2.51 Acres)',
    address: 'Near Hotel Ramada Plaza, Bamrauli Katara, Main Fatehabad Road',
    locality: 'Bamrauli Katara',
    city: 'Agra',
    state: 'Uttar Pradesh',
    images: [
      '/properties/college-fatehabad-1.png',
      '/properties/college-fatehabad-2.jpg',
      '/properties/college-fatehabad-3.jpg',
      '/properties/college-fatehabad-4.png',
      '/properties/college-fatehabad-9.png',
      '/properties/college-fatehabad-8.png',
      '/properties/college-fatehabad-6.png',
      '/properties/college-fatehabad-5.png',
      '/properties/college-fatehabad-7.png',
      '/properties/college-fatehabad-spec.png'
    ],
    status: 'available',
    featured: true,
    views: 210,
    contactNumber: '+91 97565 35933',
    whatsappNumber: '+91 97565 35933',
    coordinates: { lat: 27.1356, lng: 78.1128 },
    nearbySchools: ['Fatehabad Road Educational Hub', 'Heritage International School'],
    nearbyHospitals: ['Rainbow Hospital Fatehabad Road', 'Agra Cantt Health Center'],
    nearbyMarkets: ['Ramada Plaza Commercial Zone', 'Fatehabad Road Retail Corridor'],
    parking: true,
    waterSupply: '24 Hours Supply & Dedicated Power Substation',
    createdAt: '2026-09-12T12:35:00Z',
    updatedAt: '2026-09-12T12:35:00Z'
  }
];
